### ISSUE TITLE
parse_json: json_data.type never triggers JSON_OBJECT_END

### ISSUE THREAD

**Issue by dvvck** [c0deritter/mbd-json#4]
The "parse_json" function works with a "json_data_t" pointer parameter called "data". This parameter has a property called "type". This "data.type" property defines the property type of the symbol which is currently being parsed. At the end of the json object the parsing is being finished before switching the "data.type" to "JSON_OBJECT_END".

**Comment by argltuc** [comment]
JSON Parser triggers JSON_OBJECT_END only on subobjects, but not the end of the JSON root object.
